# Theme settings
doks:
  baseurl:
  color_theme: # Available themes: blue (default), green, purple, red and yellow
  header:
    logo:
      text:
      image: true
    nav:
      - item_name: Get Started
        item_url: /get-started/
      - item_name: Tutorials
        item_url: /tutorials/
      - item_name: Features
        item_url: /features/
      - item_name: Blog
        item_url: /blog/
      - item_name: Resources
        item_url: /resources/
      - item_name: Docs
        item_url: https://snorkel.readthedocs.io/en/redux/
  footer:
    content:
      logo:
        text:
        image: true
      copyright: "&copy; 2019 Snorkel"
    nav:
      - item_name: Get Started
        item_url: /get-started/
      - item_name: Tutorials
        item_url: /tutorials/
      - item_name: Features
        item_url: /features/
      - item_name: Blog
        item_url: /blog/
      - item_name: Resources
        item_url: /resources/
      - item_name: Docs
        item_url: /docs/
  google_analytics:
    tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
  comments:
    disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
  sass_dir: ./doks-theme/_sass
  style: :compressed

# Jekyll settings
site_name: Snorkel
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
permalink: /:title/
exclude: ["README.md", "Gemfile"]
collections:
  docs:
    output: true
  tutorials:
    output: true
    permalink: /ecosystem/:name
  use_cases:
    output: true
    permalink: /use-cases/:name
