# Theme settings
doks:
  baseurl:
  color_theme: # Available themes: blue (default), green, purple, red and yellow
  header:
    logo:
      text:
      image: true
    nav:
      - item_name: Get Started
        item_url: /get-started/
      - item_name: Use Cases
        item_url: /use-cases/
      - item_name: Features
        item_url: /features/
      - item_name: Blog
        item_url: /blog/
      - item_name: Community
        item_url: https://spectrum.chat/snorkel
      - item_name: Docs
        item_url: https://allenai.github.io/allennlp-docs/
  footer:
    content:
      logo:
        text:
        image: true
      copyright: "&copy; 2019 Snorkel"
    nav:
      - item_name: Get Started
        item_url: /get-started/
      - item_name: Use Cases
        item_url: /use-cases/
      - item_name: Ecosystem
        item_url: /ecosystem/
      - item_name: Blog
        item_url: /blog/
      - item_name: Docs
        item_url: /docs/
      - item_name: Github
        item_url: "https://github.com/HazyResearch/snorkel"
  google_analytics:
    tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
  comments:
    disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
  sass_dir: ./doks-theme/_sass
  style: :compressed

# Jekyll settings
site_name: Snorkel
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
permalink: /:title/
exclude: ['README.md', 'Gemfile']
collections:
  docs:
    output: true
  tutorials:
    output: true
    permalink: /ecosystem/:name
  use_cases:
    output: true
    permalink: /use-cases/:name
